name: Node.js CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/anaa-developers/server
            git fetch --all
            git reset --hard origin/main
            cp .env.example .env
            npm install
            npm run build

            # Check if PM2 process exists, if so, restart it, otherwise start a new one
            if pm2 describe anaa-developers-server > /dev/null; then
              pm2 restart anaa-developers-server
            else
              pm2 start npm --name "anaa-developers-server" -- run start
            fi

            # Save PM2 process list
            pm2 save
